"""Turn one flagged trace into a standalone script that re-runs the task and asserts the
failure signature. It exits 0 while the bug reproduces and 1 once it is gone — every bug the
detectors find becomes a regression test."""

import json
import os
import pathlib
import tempfile
import textwrap
from datetime import datetime, timezone

from tracepin.analyze import Analysis, TraceSummary, analyze_file
from tracepin.rootcause import top_finding

# Latency-derived detectors depend on the network of the day, not on the bug; LOW findings
# are efficiency notes, not failures. Neither belongs in a signature a script asserts on.
NONDETERMINISTIC = ("perf.latency_outlier", "perf.unaccounted_time", "perf.token_spike")


def signature(analysis: Analysis, trace_id: str) -> list[str]:
    return sorted({f.detector_id for f in analysis.findings
                   if f.trace_id == trace_id and f.severity.value != "low"
                   and not f.detector_id.startswith(NONDETERMINISTIC)})


def extract_trace(trace_path: str, trace_id: str, out: pathlib.Path) -> int:
    """Copy the spans of one trace out of a run file so the repro is readable offline."""
    n = 0
    with open(trace_path, encoding="utf-8") as src, out.open("w", encoding="utf-8") as dst:
        for line in src:
            if line.strip() and json.loads(line)["context"]["trace_id"] == trace_id:
                dst.write(line)
                n += 1
    return n


def replay(task_id: str, model: str, prompt_version: str, expected: list[str], tasks_file: str = "tasks/tasks.jsonl") -> int:
    """Re-run one task under the pinned config, analyze it, compare detector signatures."""
    from dotenv import load_dotenv

    load_dotenv(".env"); load_dotenv(".env.local")
    from tracepin.agent import run_task
    from tracepin.llm import LLM
    from tracepin.tasks import load_tasks
    from tracepin.tools import TOOL_SCHEMAS
    from tracepin.tracing import setup_tracing, shutdown_tracing

    task = next(t for t in load_tasks(tasks_file) if t.id == task_id)
    out = pathlib.Path(tempfile.mkdtemp(prefix="tracepin-repro-")) / f"{task_id}.jsonl"
    setup_tracing(model=model, prompt_version=prompt_version, jsonl_path=str(out), otlp=False)
    prompt = pathlib.Path("prompts", f"{prompt_version}.md").read_text(encoding="utf-8").strip()
    result = run_task(LLM(model=model, system_prompt=prompt, tool_schemas=TOOL_SCHEMAS), task)
    shutdown_tracing()

    analysis = analyze_file(str(out))
    got = signature(analysis, analysis.traces[0].trace_id)
    print(f"task {task_id}: success={result.success} stop_reason={result.stop_reason} iterations={result.iterations}")
    print(f"expected signature: {expected}")
    print(f"observed signature: {got}")
    missing, extra = sorted(set(expected) - set(got)), sorted(set(got) - set(expected))
    if not missing:
        print("REPRODUCED" + (f" (plus {extra})" if extra else ""))
        return 0
    print(f"NOT REPRODUCED: missing {missing}" + (f", extra {extra}" if extra else ""))
    print(f"trace written to {out}")
    return 1


def generate(analysis: Analysis, ts: TraceSummary, trace_path: str | None, out: pathlib.Path) -> pathlib.Path:
    run = analysis.run
    findings = [f for f in analysis.findings if f.trace_id == ts.trace_id]
    sig = signature(analysis, ts.trace_id)
    lines = [f"  - {f.severity.value.upper():6} {f.detector_id}: {f.title}" for f in findings]
    timeline = [f"  {i:>2}. {c['tool']:<20} {c['outcome']}" for i, c in enumerate(ts.timeline, 1)]
    out.parent.mkdir(parents=True, exist_ok=True)
    recorded = None
    if trace_path and pathlib.Path(trace_path).exists():
        recorded = out.with_name(f"{ts.task_id}_trace.jsonl")
        extract_trace(trace_path, ts.trace_id, recorded)
    top = top_finding(findings)
    headline = top.title if top else "no findings"

    script = f'''"""Repro: {ts.task_id} — {headline}

Generated by tracepin on {datetime.now(timezone.utc).strftime("%Y-%m-%d")} from trace {ts.trace_id}
Run {run["run_id"]}  model={run["model"]}  prompt={run["prompt_version"]}  commit={run["git_sha"][:10]}
Task prompt: {analysis_prompt(ts)!r}

Recorded outcome: success={ts.success} stop_reason={ts.stop_reason} iterations={ts.iterations}
Recorded tool calls:
{chr(10).join(timeline) or "  (none)"}

Findings on the recorded trace:
{chr(10).join(lines)}

Expected failure signature (detector ids that must fire; latency-based ones excluded):
  {sig}

Recorded spans: {recorded.name if recorded else "(not extracted)"}

Run:  python {out.as_posix()}
Exit: 0 if the failure reproduces, 1 if it does not (i.e. the bug is fixed).
Needs GEMINI_API_KEY in .env.local; re-runs exactly this one task under the pinned config.
"""

import sys

from tracepin.repro import replay

TASK_ID = {ts.task_id!r}
MODEL = {run["model"]!r}
PROMPT_VERSION = {run["prompt_version"]!r}
EXPECTED = {sig!r}

if __name__ == "__main__":
    sys.exit(replay(TASK_ID, MODEL, PROMPT_VERSION, EXPECTED))
'''
    out.write_text(script, encoding="utf-8")
    return out


def analysis_prompt(ts: TraceSummary) -> str:
    """Task prompt text; TraceSummary carries it from Day 3 on, older findings files fall back to tasks.jsonl."""
    p = getattr(ts, "task_prompt", "") or ""
    if p:
        return p
    try:
        for line in pathlib.Path("tasks/tasks.jsonl").read_text(encoding="utf-8").splitlines():
            if line.strip():
                d = json.loads(line)
                if d["id"] == ts.task_id:
                    return d["prompt"]
    except OSError:
        pass
    return ""
