"""Repro: t036 — search_kb rejected 2× by schema validation

Generated by tracepin on 2026-09-20 from trace 0x60edfe1edbfa602e14ed4d9735e2437a
Run c506b6cf636b  model=gemini-3.5-flash-lite  prompt=v1  commit=fb4212ef41
Task prompt: 'Look for account articles about deleting an account or GDPR. Give the publish date.'

Recorded outcome: success=True stop_reason=answered iterations=4
Recorded tool calls:
   1. search_kb            invalid_arguments
   2. search_kb            invalid_arguments
   3. search_kb            ok

Findings on the recorded trace:
  - HIGH   perf.latency_outlier: chat gemini-3.5-flash-lite took 3832504ms (3318.1× its median)
  - HIGH   perf.unaccounted_time: 3811s of 3836s wall clock (99%) is unaccounted for
  - MEDIUM args.schema_invalid: search_kb rejected 2× by schema validation
  - MEDIUM loop.retry_storm: search_kb retried 2× after failures, eventually succeeded
  - LOW    error.self_correction_cost: recovered from invalid_arguments on search_kb after 2 extra turn(s)

Expected failure signature (detector ids that must fire; latency-based ones excluded):
  ['args.schema_invalid', 'loop.retry_storm']

Recorded spans: t036_trace.jsonl

Run:  python repro/t036_repro.py
Exit: 0 if the failure reproduces, 1 if it does not (i.e. the bug is fixed).
Needs GEMINI_API_KEY in .env.local; re-runs exactly this one task under the pinned config.
"""

import sys

from tracepin.repro import replay

TASK_ID = 't036'
MODEL = 'gemini-3.5-flash-lite'
PROMPT_VERSION = 'v1'
EXPECTED = ['args.schema_invalid', 'loop.retry_storm']

if __name__ == "__main__":
    sys.exit(replay(TASK_ID, MODEL, PROMPT_VERSION, EXPECTED))
