"""Repro: t037 — search_kb called 4× varying only query.filters.category — every call came back empty or failed

Generated by tracepin on 2026-09-20 from trace 0x7274597ef22d87765c60774b1055839e
Run 9d7035e7b694  model=gemini-3.1-flash-lite  prompt=v1  commit=5a9512dea4
Task prompt: 'Cancel order ORD-1002 for me.'

Recorded outcome: success=False stop_reason=max_iterations iterations=8
Recorded tool calls:
   1. cancel_order         unknown_tool
   2. search_kb            invalid_arguments
   3. search_kb            invalid_arguments
   4. search_kb            ok
   5. fetch_order_status   ok
   6. search_kb            ok
   7. search_kb            ok
   8. search_kb            ok

Findings on the recorded trace:
  - HIGH   tool.unknown_name: called non-existent tool cancel_order — still advertised in the system prompt
  - HIGH   perf.latency_outlier: chat gemini-3.1-flash-lite took 72055ms (31.7× its median)
  - HIGH   loop.near_duplicate: search_kb called 4× varying only query.filters.category — every call came back empty or failed
  - MEDIUM args.schema_invalid: search_kb rejected 2× by schema validation
  - MEDIUM error.no_progress: exhausted 8 iterations: 8 distinct call(s) in 8 attempts — exploring
  - LOW    error.self_correction_cost: recovered from unknown_tool on cancel_order after 3 extra turn(s)
  - LOW    error.self_correction_cost: recovered from invalid_arguments on search_kb after 2 extra turn(s)

Expected failure signature (detector ids that must fire; latency-based ones excluded):
  ['args.schema_invalid', 'error.no_progress', 'loop.near_duplicate', 'tool.unknown_name']

Recorded spans: t037_trace.jsonl

Run:  python repro/t037_repro.py
Exit: 0 if the failure reproduces, 1 if it does not (i.e. the bug is fixed).
Needs GEMINI_API_KEY in .env.local; re-runs exactly this one task under the pinned config.
"""

import sys

from tracepin.repro import replay

TASK_ID = 't037'
MODEL = 'gemini-3.1-flash-lite'
PROMPT_VERSION = 'v1'
EXPECTED = ['args.schema_invalid', 'error.no_progress', 'loop.near_duplicate', 'tool.unknown_name']

if __name__ == "__main__":
    sys.exit(replay(TASK_ID, MODEL, PROMPT_VERSION, EXPECTED))
