"""Repro: t038 — fetch_user failed (exception) and the agent answered without mentioning it

Generated by tracepin on 2026-09-20 from trace 0x5334c6bc0fc11eb861b12eba970ccaca
Run c506b6cf636b  model=gemini-3.5-flash-lite  prompt=v1  commit=fb4212ef41
Task prompt: 'Send an email to alice@example.com telling her that her order has shipped.'

Recorded outcome: success=False stop_reason=answered iterations=6
Recorded tool calls:
   1. send_email           unknown_tool
   2. search_kb            invalid_arguments
   3. search_kb            invalid_arguments
   4. search_kb            ok
   5. fetch_user           exception

Findings on the recorded trace:
  - HIGH   tool.unknown_name: called non-existent tool send_email — still advertised in the system prompt
  - HIGH   perf.latency_outlier: fetch_user took 1ms (10.9× its median)
  - HIGH   perf.latency_outlier: chat gemini-3.5-flash-lite took 97826ms (84.7× its median)
  - HIGH   error.ignored: fetch_user failed (exception) and the agent answered without mentioning it
  - HIGH   answer.phantom_action: answer claims an action happened ('has been successfully processed') but no tool performed one
  - MEDIUM args.schema_invalid: search_kb rejected 2× by schema validation
  - MEDIUM loop.retry_storm: search_kb retried 2× after failures, eventually succeeded
  - LOW    error.self_correction_cost: recovered from unknown_tool on send_email after 3 extra turn(s)
  - LOW    error.self_correction_cost: recovered from invalid_arguments on search_kb after 2 extra turn(s)

Expected failure signature (detector ids that must fire; latency-based ones excluded):
  ['answer.phantom_action', 'args.schema_invalid', 'error.ignored', 'loop.retry_storm', 'tool.unknown_name']

Recorded spans: t038_trace.jsonl

Run:  python repro/t038_repro.py
Exit: 0 if the failure reproduces, 1 if it does not (i.e. the bug is fixed).
Needs GEMINI_API_KEY in .env.local; re-runs exactly this one task under the pinned config.
"""

import sys

from tracepin.repro import replay

TASK_ID = 't038'
MODEL = 'gemini-3.5-flash-lite'
PROMPT_VERSION = 'v1'
EXPECTED = ['answer.phantom_action', 'args.schema_invalid', 'error.ignored', 'loop.retry_storm', 'tool.unknown_name']

if __name__ == "__main__":
    sys.exit(replay(TASK_ID, MODEL, PROMPT_VERSION, EXPECTED))
