"""Repro: t041 — search_kb called 6× varying only query.terms[0] — every call came back empty or failed

Generated by tracepin on 2026-09-20 from trace 0x72375c332b22a98c6fe849760012b88a
Run 9d7035e7b694  model=gemini-3.1-flash-lite  prompt=v1  commit=5a9512dea4
Task prompt: 'List all users who are on the pro plan.'

Recorded outcome: success=False stop_reason=max_iterations iterations=8
Recorded tool calls:
   1. search_kb            invalid_arguments
   2. search_kb            invalid_arguments
   3. search_kb            ok
   4. search_kb            ok
   5. search_kb            ok
   6. search_kb            ok
   7. search_kb            ok
   8. search_kb            ok

Findings on the recorded trace:
  - HIGH   perf.latency_outlier: chat gemini-3.1-flash-lite took 93793ms (41.3× its median)
  - HIGH   perf.latency_outlier: chat gemini-3.1-flash-lite took 47527ms (20.9× its median)
  - HIGH   loop.near_duplicate: search_kb called 6× varying only query.terms[0] — every call came back empty or failed
  - MEDIUM args.schema_invalid: search_kb rejected 2× by schema validation
  - MEDIUM args.type_confusion: search_kb called with wrong-typed argument (query.terms)
  - MEDIUM error.no_progress: exhausted 8 iterations: 8 distinct call(s) in 8 attempts — exploring
  - MEDIUM perf.latency_outlier: chat gemini-3.1-flash-lite took 14941ms (6.6× its median)
  - LOW    error.self_correction_cost: recovered from invalid_arguments on search_kb after 2 extra turn(s)

Expected failure signature (detector ids that must fire; latency-based ones excluded):
  ['args.schema_invalid', 'args.type_confusion', 'error.no_progress', 'loop.near_duplicate']

Recorded spans: t041_trace.jsonl

Run:  python repro/t041_repro.py
Exit: 0 if the failure reproduces, 1 if it does not (i.e. the bug is fixed).
Needs GEMINI_API_KEY in .env.local; re-runs exactly this one task under the pinned config.
"""

import sys

from tracepin.repro import replay

TASK_ID = 't041'
MODEL = 'gemini-3.1-flash-lite'
PROMPT_VERSION = 'v1'
EXPECTED = ['args.schema_invalid', 'args.type_confusion', 'error.no_progress', 'loop.near_duplicate']

if __name__ == "__main__":
    sys.exit(replay(TASK_ID, MODEL, PROMPT_VERSION, EXPECTED))
